apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starter-kit-apps
  namespace: argocd
spec:
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  source:
    path: k8s-manifest/argocd/manifests/apps/demo-app
    repoURL: https://github.com/kirillzekn/DevSecOps-project-1.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SyncWave=0