name: CD Pipeline

on: workflow_dispatch

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          repository: 'kirillzekn/DevSecOps-project-1'
          path: ./repo
      - name: Generate Kubernetes Manifests with Helm
        env:
          NAMESPACE: demo-app
          IMAGE_REPO: "${{ secrets.DOCKERHUB_USERNAME }}/"
          IMAGE_NAME: devsecops_project_1
        run: |
          ls -l
          pwd
          cd repo/k8s-manifest/demo-app
          pwd
          ls -l
          helm template release . --debug --set namespace=${NAMESPACE} --set image.repository=${IMAGE_REPO}${IMAGE_NAME} --set image.tag=${{ github.sha }} --output-dir ./..
      - name: Update ArgoCD Manifests
        run: |
          pwd
          ls -ltr
          # cd repo/k8s-manifest/arogcd
          # cd ..
          # mkdir -p argocd/manifests/apps/demo-app
          # rm -rf argocd/manifests/apps/demo-app/*
          # mv ./demo-app/templates/* argocd/manifests/apps/demo-app/
          # git config --global user.email "zelentsovkir@gmail.com"
          # git config --global user.name "CI_CD Bot"
          # cd argocd
          # git add .
          # git commit -m "Update demo-app commit ${{ github.sha }} "
          # git remote set-url origin https://github.com/kirillzekn/DevSecOps-project-1.git
          # git push origin main