name: Terraform Init Backend

on: workflow_dispatch

permissions:
  contents: read
  id-token: write

jobs:
  deploy_backend_for_terraform:
    name: 'AZ CLI Terraform Backend'
    runs-on: ubuntu-latest
    #environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          
    - name: Create RG and Storage account
      #export MY_STORAGE_ACCOUNT_NAME="tfstate$(date +%m%d%Y)"
      run: |
        export MY_RESOURCE_GROUP_NAME="rg-terraform-state"
        export REGION="westeurope"
        
        export MY_STORAGE_ACCOUNT_NAME="tfstate02132025"
        export MY_CONTAINER_NAME="tfstate"
                
        if [ "$(az group list -o tsv --query "[?name=='$MY_RESOURCE_GROUP_NAME'].name")" = "" ];
        then
            echo "No RG was found."
            az group create --name $MY_RESOURCE_GROUP_NAME --location $REGION
        else
            echo "RG was found."
        fi

        if [ "$(az storage account list -o tsv --query "[?name=='$MY_STORAGE_ACCOUNT_NAME'].name")" = "" ];
        then
            echo "No storageaccount was found."
            az storage account create --resource-group $MY_RESOURCE_GROUP_NAME --name $MY_STORAGE_ACCOUNT_NAME --sku Standard_LRS
            az storage container create --name $MY_CONTAINER_NAME --account-name $MY_STORAGE_ACCOUNT_NAME
        else
            echo "StorageAccount was found."
        fi
      