name: Terraform Destroy

on: workflow_dispatch

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform Destroy'
    env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    runs-on: ubuntu-latest
  
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
        
    # Install the latest version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        terraform init

    - name: Terraform destroy
      if: github.ref == 'refs/heads/"master"' && github.event_name == 'push'
      run: terraform destroy -auto-approve -input=false 
      